[versions]
shadow = "9.3.1"
spotless = "8.2.1"
owasp = "12.2.0"

jda = "6.3.0"
logback = "1.5.28"
dotenv = "3.2.0"
hikari = "7.0.2"
sqlite = "3.51.1.0"

[libraries]
jda = { group = "net.dv8tion", name = "JDA", version.ref = "jda" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
dotenv = { group = "io.github.cdimascio", name = "dotenv-java", version.ref = "dotenv" }
hikari = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
owasp = { id = "org.owasp.dependencycheck", version.ref = "owasp" }
